//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace unoProyect.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("unoProyect.Properties.Resources.es", typeof(Resources_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color actual.
        /// </summary>
        public static string actualColor {
            get {
                return ResourceManager.GetString("actualColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azul.
        /// </summary>
        public static string blue {
            get {
                return ResourceManager.GetString("blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar contraseña.
        /// </summary>
        public static string changePassword {
            get {
                return ResourceManager.GetString("changePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string chat {
            get {
                return ResourceManager.GetString("chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elige un color.
        /// </summary>
        public static string chooseColor {
            get {
                return ResourceManager.GetString("chooseColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentido actual.
        /// </summary>
        public static string direction {
            get {
                return ResourceManager.GetString("direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        public static string enter {
            get {
                return ResourceManager.GetString("enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede inciar la partida con menos de 2 o más de 5 jugadores en la sala de estar.
        /// </summary>
        public static string errorStartGamePlayers {
            get {
                return ResourceManager.GetString("errorStartGamePlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olvidé mi contraseña.
        /// </summary>
        public static string forgetMyPassword {
            get {
                return ResourceManager.GetString("forgetMyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de amigos.
        /// </summary>
        public static string friendsList {
            get {
                return ResourceManager.GetString("friendsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNO.
        /// </summary>
        public static string game {
            get {
                return ResourceManager.GetString("game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verde.
        /// </summary>
        public static string green {
            get {
                return ResourceManager.GetString("green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro exitoso :).
        /// </summary>
        public static string informationSuccesfullSignUp {
            get {
                return ResourceManager.GetString("informationSuccesfullSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario ocupado, intenta con otro.
        /// </summary>
        public static string informationUsernameDuplicate {
            get {
                return ResourceManager.GetString("informationUsernameDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al momento de registrar tu cuenta, intenta de nuevo más tarde.
        /// </summary>
        public static string informationWrongSignUp {
            get {
                return ResourceManager.GetString("informationWrongSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Te enviaremos un código a tu correo electrónico para cambiar tu contraseña.
        /// </summary>
        public static string instructionChangePasswordCode {
            get {
                return ResourceManager.GetString("instructionChangePasswordCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿No ves el código? Revisa tu carpeta de correos no deseados.
        /// </summary>
        public static string instructionCheckSpam {
            get {
                return ResourceManager.GetString("instructionCheckSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el código:.
        /// </summary>
        public static string instructionEnterConfirmCode {
            get {
                return ResourceManager.GetString("instructionEnterConfirmCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertar código de invitación.
        /// </summary>
        public static string instructionEnterInvitationCode {
            get {
                return ResourceManager.GetString("instructionEnterInvitationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresa nueva contraseña.
        /// </summary>
        public static string instructionEnterNewPassword {
            get {
                return ResourceManager.GetString("instructionEnterNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar nombre de usuario.
        /// </summary>
        public static string instructionEnterUsername {
            get {
                return ResourceManager.GetString("instructionEnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Estás seguro que quieres abandonar la partida?.
        /// </summary>
        public static string instructionExitGame {
            get {
                return ResourceManager.GetString("instructionExitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repite la nueva contraseña.
        /// </summary>
        public static string instructionRepeatPassword {
            get {
                return ResourceManager.GetString("instructionRepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, selecciona una carta.
        /// </summary>
        public static string instructionSelectACard {
            get {
                return ResourceManager.GetString("instructionSelectACard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar código por correo electrónico.
        /// </summary>
        public static string instructionSendCodeByEmail {
            get {
                return ResourceManager.GetString("instructionSendCodeByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Te enviaremos un código a tu correo electrónico para confirmar el registro.
        /// </summary>
        public static string instructionSendConfirmCode {
            get {
                return ResourceManager.GetString("instructionSendConfirmCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carta inválida.
        /// </summary>
        public static string invalidCard {
            get {
                return ResourceManager.GetString("invalidCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico o contraseña inválidos.
        /// </summary>
        public static string invalidPasswordOrEmail {
            get {
                return ResourceManager.GetString("invalidPasswordOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expulsar de la partida.
        /// </summary>
        public static string Kickfromthegame {
            get {
                return ResourceManager.GetString("Kickfromthegame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sala de espera.
        /// </summary>
        public static string lobby {
            get {
                return ResourceManager.GetString("lobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis cartas.
        /// </summary>
        public static string myCards {
            get {
                return ResourceManager.GetString("myCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear partida.
        /// </summary>
        public static string newGame {
            get {
                return ResourceManager.GetString("newGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pueden dejar campos vacíos.
        /// </summary>
        public static string notEmptyFields {
            get {
                return ResourceManager.GetString("notEmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ahora jugando.
        /// </summary>
        public static string nowPlaying {
            get {
                return ResourceManager.GetString("nowPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jugar como invitado.
        /// </summary>
        public static string playAsGuest {
            get {
                return ResourceManager.GetString("playAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jugadores.
        /// </summary>
        public static string players {
            get {
                return ResourceManager.GetString("players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitar amigos.
        /// </summary>
        public static string playWithFriends {
            get {
                return ResourceManager.GetString("playWithFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rojo.
        /// </summary>
        public static string red {
            get {
                return ResourceManager.GetString("red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitar nuevo código.
        /// </summary>
        public static string requestNewCode {
            get {
                return ResourceManager.GetString("requestNewCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar código de invitación.
        /// </summary>
        public static string sendCode {
            get {
                return ResourceManager.GetString("sendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalizar perfil.
        /// </summary>
        public static string settingsProfile {
            get {
                return ResourceManager.GetString("settingsProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrarse.
        /// </summary>
        public static string signUp {
            get {
                return ResourceManager.GetString("signUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo sentimos....
        /// </summary>
        public static string sorry {
            get {
                return ResourceManager.GetString("sorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar partida.
        /// </summary>
        public static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código de la partida es:.
        /// </summary>
        public static string theGameCodeIs {
            get {
                return ResourceManager.GetString("theGameCodeIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usar carta.
        /// </summary>
        public static string useCard {
            get {
                return ResourceManager.GetString("useCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pudimos encontrar el nombre de usuario ingresado.
        /// </summary>
        public static string usernameNotFound {
            get {
                return ResourceManager.GetString("usernameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ups! Debes tomar una carta de la pila antes de pasar.
        /// </summary>
        public static string warningSkip {
            get {
                return ResourceManager.GetString("warningSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido.
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credenciales incorrectas.
        /// </summary>
        public static string wrongCredentials {
            get {
                return ResourceManager.GetString("wrongCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo electrónico ingresado no es válido.
        /// </summary>
        public static string wrongEmail {
            get {
                return ResourceManager.GetString("wrongEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amarillo.
        /// </summary>
        public static string yellow {
            get {
                return ResourceManager.GetString("yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sí.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
