//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace unoProyect.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("unoProyect.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Actual color.
        /// </summary>
        public static string actualColor {
            get {
                return ResourceManager.GetString("actualColor", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Blue.
        /// </summary>
        public static string blue {
            get {
                return ResourceManager.GetString("blue", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Change password.
        /// </summary>
        public static string changePassword {
            get {
                return ResourceManager.GetString("changePassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string chat {
            get {
                return ResourceManager.GetString("chat", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Choose a color.
        /// </summary>
        public static string chooseColor {
            get {
                return ResourceManager.GetString("chooseColor", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Game Direction.
        /// </summary>
        public static string direction {
            get {
                return ResourceManager.GetString("direction", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string enter {
            get {
                return ResourceManager.GetString("enter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a A game can&apos;t be started with less than or more than 5 players in the lobby.
        /// </summary>
        public static string errorStartGamePlayers {
            get {
                return ResourceManager.GetString("errorStartGamePlayers", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Forget my password.
        /// </summary>
        public static string forgetMyPassword {
            get {
                return ResourceManager.GetString("forgetMyPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Friends list.
        /// </summary>
        public static string friendsList {
            get {
                return ResourceManager.GetString("friendsList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UNO.
        /// </summary>
        public static string game {
            get {
                return ResourceManager.GetString("game", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Green.
        /// </summary>
        public static string green {
            get {
                return ResourceManager.GetString("green", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Successfull sign up :).
        /// </summary>
        public static string informationSuccesfullSignUp {
            get {
                return ResourceManager.GetString("informationSuccesfullSignUp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Username already registered, try with another.
        /// </summary>
        public static string informationUsernameDuplicate {
            get {
                return ResourceManager.GetString("informationUsernameDuplicate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, try again later.
        /// </summary>
        public static string informationWrongSignUp {
            get {
                return ResourceManager.GetString("informationWrongSignUp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to We&apos;ll send you a code by email to change your password.
        /// </summary>
        public static string instructionChangePasswordCode {
            get {
                return ResourceManager.GetString("instructionChangePasswordCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t see the code? Check your spam.
        /// </summary>
        public static string instructionCheckSpam {
            get {
                return ResourceManager.GetString("instructionCheckSpam", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter confirm code:.
        /// </summary>
        public static string instructionEnterConfirmCode {
            get {
                return ResourceManager.GetString("instructionEnterConfirmCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter Invitation Code.
        /// </summary>
        public static string instructionEnterInvitationCode {
            get {
                return ResourceManager.GetString("instructionEnterInvitationCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter new password.
        /// </summary>
        public static string instructionEnterNewPassword {
            get {
                return ResourceManager.GetString("instructionEnterNewPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter username.
        /// </summary>
        public static string instructionEnterUsername {
            get {
                return ResourceManager.GetString("instructionEnterUsername", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit?.
        /// </summary>
        public static string instructionExitGame {
            get {
                return ResourceManager.GetString("instructionExitGame", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Repeat your new password.
        /// </summary>
        public static string instructionRepeatPassword {
            get {
                return ResourceManager.GetString("instructionRepeatPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select a card.
        /// </summary>
        public static string instructionSelectACard {
            get {
                return ResourceManager.GetString("instructionSelectACard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Send code by email.
        /// </summary>
        public static string instructionSendCodeByEmail {
            get {
                return ResourceManager.GetString("instructionSendCodeByEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to We&apos;ll send you a code by email to confirm your account.
        /// </summary>
        public static string instructionSendConfirmCode {
            get {
                return ResourceManager.GetString("instructionSendConfirmCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid card.
        /// </summary>
        public static string invalidCard {
            get {
                return ResourceManager.GetString("invalidCard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email or password invalids.
        /// </summary>
        public static string invalidPasswordOrEmail {
            get {
                return ResourceManager.GetString("invalidPasswordOrEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kick from the game.
        /// </summary>
        public static string Kickfromthegame {
            get {
                return ResourceManager.GetString("Kickfromthegame", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lobby.
        /// </summary>
        public static string lobby {
            get {
                return ResourceManager.GetString("lobby", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to My cards.
        /// </summary>
        public static string myCards {
            get {
                return ResourceManager.GetString("myCards", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New game.
        /// </summary>
        public static string newGame {
            get {
                return ResourceManager.GetString("newGame", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t leave empty fields.
        /// </summary>
        public static string notEmptyFields {
            get {
                return ResourceManager.GetString("notEmptyFields", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Now playing.
        /// </summary>
        public static string nowPlaying {
            get {
                return ResourceManager.GetString("nowPlaying", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Play as guest.
        /// </summary>
        public static string playAsGuest {
            get {
                return ResourceManager.GetString("playAsGuest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string players {
            get {
                return ResourceManager.GetString("players", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Play with friends.
        /// </summary>
        public static string playWithFriends {
            get {
                return ResourceManager.GetString("playWithFriends", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string red {
            get {
                return ResourceManager.GetString("red", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Request new code.
        /// </summary>
        public static string requestNewCode {
            get {
                return ResourceManager.GetString("requestNewCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Send code.
        /// </summary>
        public static string sendCode {
            get {
                return ResourceManager.GetString("sendCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings profile.
        /// </summary>
        public static string settingsProfile {
            get {
                return ResourceManager.GetString("settingsProfile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string signUp {
            get {
                return ResourceManager.GetString("signUp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry....
        /// </summary>
        public static string sorry {
            get {
                return ResourceManager.GetString("sorry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The game code is: .
        /// </summary>
        public static string theGameCodeIs {
            get {
                return ResourceManager.GetString("theGameCodeIs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use card.
        /// </summary>
        public static string useCard {
            get {
                return ResourceManager.GetString("useCard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t find the username entered..
        /// </summary>
        public static string usernameNotFound {
            get {
                return ResourceManager.GetString("usernameNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ups! You must take a card from the stack before skip.
        /// </summary>
        public static string warningSkip {
            get {
                return ResourceManager.GetString("warningSkip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Wrong credentials.
        /// </summary>
        public static string wrongCredentials {
            get {
                return ResourceManager.GetString("wrongCredentials", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The email is invalid.
        /// </summary>
        public static string wrongEmail {
            get {
                return ResourceManager.GetString("wrongEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string yellow {
            get {
                return ResourceManager.GetString("yellow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
